services:
  frontend:
    image: angular-nodejs:latest
    build: 
      context: ./angular-app
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
  backend:
    image: dotnet-api:latest    
    build:
      context: ./dotnet-crud-api
      dockerfile: ./Dockerfile
    ports:
      - 5010:5000
      - 5011:5001
